version: '3.4'

services:

    rabbitmq_emailcleaner:
        image: "rabbitmq:management-alpine"
        container_name: rabbitmq_emailcleaner
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - type: bind
              source: ./rabbitmq/enabled_plugins
              target: /etc/rabbitmq/enabled-plugins
            - type: bind
              source: ./rabbitmq/rabbitmq.config
              target: /etc/rabbitmq/rabbitmq.config
            - type: bind
              source: ./rabbitmq/definitions.json
              target: /etc/rabbitmq/definitions.json

    mail-collector:
        container_name: mail-collector
        build:
            context: .
            dockerfile: MailCollectorService/Dockerfile
        depends_on:
            - rabbitmq_emailcleaner
        ports:
            - "5201:5201"
        volumes:
            - ./logs:/app/logs
            - ./MailCollectorService/token.json:/app/token.json

    mail-provider:
        container_name: mail-provider
        build:
            context: .
            dockerfile: MailProviderService/Dockerfile
        depends_on:
            - rabbitmq_emailcleaner
        ports:
            - "5202:5202" 
        volumes:
            - ./logs:/app/logs

    #apigateway:
    #    container_name: apigateway
    #    ports:
    #        - "5200:5200"
    #    build:
    #        context: .
    #        dockerfile: APIGateway/Dockerfile
    #    depends_on:
    #        - mail-collector
    #        - mail-provider
    #    volumes:
    #        - ./logs:/app/logs
